# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jrshin Github Blog
email: jrshin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, My name is Jrshin. I'm just another data anylist and web designer
  from Chicago who loves coding and fixing things.
  This blog is an my works. It will use lots of HTML, CSS and a little bit
  Javascript, Json. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jrshin.github.io/" # the base hostname & protocol for your site
twitter_username: JrshinChen
github_username:  jrshin

# Build settings
markdown: kramdown
